# Generated by Django 5.2.7 on 2025-10-15 23:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoResiduo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Nome do tipo de resíduo, ex: 'Pilhas'", max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, help_text='Breve descrição sobre o descarte correto deste item')),
                ('reciclavel', models.BooleanField(default=True, help_text='Marque se esse item é comumente reciclável')),
            ],
            options={
                'verbose_name': 'Tipo de Resíduo',
                'verbose_name_plural': 'Tipos de Resíduos',
            },
        ),
        migrations.CreateModel(
            name='PontoColeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Nome do local, ex: 'Ecoponto do Jorge'", max_length=255)),
                ('endereco', models.CharField(help_text='Endereço completo do ecoponto', max_length=255)),
                ('telefone', models.CharField(blank=True, help_text='Telefone de contato (opcional).', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='E-mail de contato (opcional).', max_length=254)),
                ('horario_funcionamento', models.CharField(blank=True, help_text="Horários de funcionamento, ex: 'Seg-Sex 08:00-18:00'", max_length=255)),
                ('localizacao', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('tipos_residuos_aceitos', models.ManyToManyField(to='api.tiporesiduo')),
            ],
            options={
                'verbose_name': 'Ponto de Coleta',
                'verbose_name_plural': 'Pontos de Coleta',
            },
        ),
        migrations.CreateModel(
            name='Cooperativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('responsavel', models.CharField(blank=True, max_length=255)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('horario_funcionamento', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('status_cadastro', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=10)),
                ('localizacao', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Localização da sede da cooperativa.', null=True, srid=4326)),
                ('tipos_residuos_aceitos', models.ManyToManyField(to='api.tiporesiduo')),
            ],
            options={
                'verbose_name': 'Cooperativa',
                'verbose_name_plural': 'Cooperativas',
            },
        ),
    ]
